services:
  - type: web
    name: moosic-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://moosic.vercel.app
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: BACKEND_URL
        sync: false
      - key: ENVIRONMENT
        value: production 